export class CommonConstants{
  static readonly FULL_LENGTH:string = '100%'
  static readonly LOGIN_BUTTON_WIDTH:string = '90%'
  static readonly COLUMN_SPACE:string = '20vp'
  static readonly LIKELY_LENGTH:string = '100vp'

  //percent
  static readonly PERCENT_8:string = '8%';
  static readonly PERCENT_10:string = '10%';
  static readonly PERCENT_20:string = '20%';
  static readonly PERCENT_30:string = '30%';
  static readonly PERCENT_40:string = '40%';
  static readonly PERCENT_50:string = '50%';
  static readonly PERCENT_60:string = '60%';
  static readonly PERCENT_70:string = '70%';
  static readonly PERCENT_80:string = '80%';
  static readonly PERCENT_90:string = '90%';
  static readonly PERCENT_94:string = '94%';
  static readonly PERCENT_100:string = '100%';

  // default_value
  static readonly DEFAULT_0:number = 0;
  static readonly DEFAULT_1:number = 1;
  static readonly DEFAULT_2:number = 2;
  static readonly DEFAULT_4:number = 4;
  static readonly DEFAULT_8:number = 8;
  static readonly DEFAULT_10:number = 10;
  static readonly DEFAULT_12:number = 12;
  static readonly DEFAULT_14:number = 14;
  static readonly DEFAULT_16:number = 16;
  static readonly DEFAULT_18:number = 18;
  static readonly DEFAULT_20:number = 20;
  static readonly DEFAULT_24:number = 24;
  static readonly DEFAULT_28:number = 28;
  static readonly DEFAULT_32:number = 32;
  static readonly DEFAULT_40:number = 40;
  static readonly DEFAULT_48:number = 48;
  static readonly DEFAULT_56:number = 56;
  static readonly DEFAULT_60:number = 60;
  static readonly DEFAULT_70:number = 70;
  static readonly DEFAULT_80:number = 80;
  static readonly DEFAULT_100:number = 100;
  static readonly DEFAULT_150:number = 150;
  static readonly DEFAULT_200:number = 200;
  static readonly DEFAULT_222:number = 222;
  static readonly DEFAULT_300:number = 300;
}